controller_manager:
  ros__parameters:

    update_rate: 60 # Hz

    agv1_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv1_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
velocity_controller:
  ros__parameters:
    joints:
      - agv1_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position