controller_manager:
  ros__parameters:

    update_rate: 60 # Hz

    agv4_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv4_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
velocity_controller:
  ros__parameters:
    joints:
      - agv4_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position