agv1/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: velocity_controllers/JointGroupVelocityController
    
agv1/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position

agv2/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: velocity_controllers/JointGroupVelocityController
    
agv2/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position

agv3/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: velocity_controllers/JointGroupVelocityController
    
agv3/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position


agv4/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    agv_controller:
      type: velocity_controllers/JointGroupVelocityController
    
agv4/agv_controller:
  ros__parameters:
    joints:
      - agv_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position




