assembly/controller_manager:
  ros__parameters:

    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gantry_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


assembly/arm_joint_trajectory_controller:
  ros__parameters:
    joints:
      - assembly_shoulder_pan_joint
      - assembly_shoulder_lift_joint
      - assembly_elbow_joint
      - assembly_wrist_1_joint
      - assembly_wrist_2_joint
      - assembly_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      assembly_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      assembly_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      assembly_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      assembly_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      assembly_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      assembly_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }


assembly/gantry_joint_trajectory_controller:
  ros__parameters:
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      small_long_joint: {trajectory: 0.1, goal: 0.1}
      torso_rail_joint:  {trajectory: 0.1, goal: 0.1}
      torso_base_main_joint: {trajectory: 0.1, goal: 0.1}
