bins:
  bin1:
    pose:
      xyz: [-1.898993, 3.379920, 0.72]
      rpy: [0, 0, pi]
  bin2:
    pose:
      xyz: [-1.898993, 2.565006, 0.72]
      rpy: [0, 0, pi]
  bin3:
    pose:
      xyz: [-2.651690, 2.565006, 0.72]
      rpy: [0, 0, pi]
  bin4:
    pose:
      xyz: [-2.651690, 3.379920, 0.72]
      rpy: [0, 0, pi]
  bin5:
    pose:
      xyz: [-1.898993, -3.37992, 0.72]
      rpy: [0, 0, pi]
  bin6:
    pose:
      xyz: [-1.898993, -2.56501, 0.72]
      rpy: [0, 0, pi]
  bin7:
    pose:
      xyz: [-2.651690, -2.56501, 0.72]
      rpy: [0, 0, pi]
  bin8:
    pose:
      xyz: [-2.651690, -3.37992, 0.72]
      rpy: [0, 0, pi]