bins:
  bin1:
    pose:
      xyz: [-1.898993, 3.379920, 0.72]
      rpy: [0, 0, pi]
  bin2:
    pose:
      xyz: [-1.898993, 2.565006, 0.72]
      rpy: [0, 0, pi]
  bin3:
    pose:
      xyz: [-2.651690, 2.565006, 0.72]
      rpy: [0, 0, pi]
  bin4:
    pose:
      xyz: [-2.651690, 3.379920, 0.72]
      rpy: [0, 0, pi]
  bin5:
    pose:
      xyz: [-1.898993, -3.37992, 0.72]
      rpy: [0, 0, pi]
  bin6:
    pose:
      xyz: [-1.898993, -2.56501, 0.72]
      rpy: [0, 0, pi]
  bin7:
    pose:
      xyz: [-2.651690, -2.56501, 0.72]
      rpy: [0, 0, pi]
  bin8:
    pose:
      xyz: [-2.651690, -3.37992, 0.72]
      rpy: [0, 0, pi]

assembly_stations:
  as1:
    table:
      pose:
        xyz: [-7.3, 3, 0]
        rpy: [0, 0, 0]
    insert:
      pose:
        xyz: [-0.4, 0, 1.011]
        rpy: [0, 0, 0]
  as2:
    table:
      pose:
        xyz: [-12.3, 3, 0]
        rpy: [0, 0, 0]
    insert:
      pose:
        xyz: [-0.4, 0, 1.011]
        rpy: [0, 0, 0]
  as3:
    table:
      pose:
        xyz: [-7.3, -3, 0]
        rpy: [0, 0, 0]
    insert:
      pose:
        xyz: [-0.4, 0, 1.011]
        rpy: [0, 0, 0]
  as4:
    table:
      pose:
        xyz: [-12.3, -3, 0]
        rpy: [0, 0, 0]
    insert:
      pose:
        xyz: [-0.4, 0, 1.011]
        rpy: [0, 0, 0]

kit_tray_stations:
  kts1:
    table:
      pose:
        xyz: [-1.3, -5.84, 0.725]
        rpy: [0, 0, 'pi']
    tool_changer_parts:
      pose:
        xyz: [-0.2, -0.435, -0.07]
        rpy: [0, 0, 0]
    tool_changer_trays:
      pose:
        xyz: [0.2, -0.435, -0.07]
        rpy: [0, 0, 0]
  kts2:
    table:
      pose:
        xyz: [-1.3, 5.84, 0.725]
        rpy: [0, 0, 0]
    tool_changer_parts:
      pose:
        xyz: [-0.2, -0.435, -0.07]
        rpy: [0, 0, 0]
    tool_changer_trays:
      pose:
        xyz: [0.2, -0.435, -0.07]
        rpy: [0, 0, 0]
