sensors:
  breakbeam_1:
    type: break_beam
    pose:
      xyz: [-0.35, 3, 0.95]
      rpy: [0, 0, pi]

  breakbeam_2:
    type: break_beam
    pose:
      xyz: [-0.35, 2.5, 0.95]
      rpy: [0, 0, pi]

  proximity_sensor_0:
    type: proximity_sensor
    pose:
      xyz: [-0.573, 2.84, 1]
      rpy: [pi/2, pi/6, pi/2]

  laser_profiler_0:
    type: laser_profiler
    pose:
      xyz: [-0.573, 1.486, 1.526]
      rpy: [pi/2, pi/2, 0]

  # depth_camera_0:
  #   type: depth_camera
  #   visualize_fov: false
  #   pose:
  #     xyz: [-1.9, 2.565, 1.6]
  #     rpy: [0, 'pi/2', 'pi/2']

  rgb_camera_0:
    type: rgb_camera
    pose:
      xyz: [-1.9, 2.565, 1.6]
      rpy: [0, 'pi/2', 'pi/2']
  