controller_manager:
  ros__parameters:


    update_rate: 1000 # Hz


    gantry_controller:
      type: effort_controllers/JointTrajectoryController


gantry_controller:
  ros__parameters:
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      small_long_joint: {trajectory: 0.1, goal: 0.1}
      torso_rail_joint:  {trajectory: 0.1, goal: 0.1}
      torso_base_main_joint: {trajectory: 0.1, goal: 0.1}
