controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - small_long_joint
    - torso_rail_joint
    - torso_base_main_joint
    - ceiling_shoulder_pan_joint
    - ceiling_shoulder_lift_joint
    - ceiling_elbow_joint
    - ceiling_wrist_1_joint
    - ceiling_wrist_2_joint
    - ceiling_wrist_3_joint
    