controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - linear_actuator
    - floor_shoulder_pan_joint
    - floor_shoulder_lift_joint
    - floor_elbow_joint
    - floor_wrist_1_joint
    - floor_wrist_2_joint
    - floor_wrist_3_joint
    
